---
- name: Desktop configuration
  hosts: test
  # connection: local
  #remote_user: <remote_user>
  # vars:
  #   username_name: "{{ ansible_user_id }}"

  roles:

    - role: gantsign.oh-my-zsh
      vars:
        oh_my_zsh_theme: robbyrussell
        oh_my_zsh_plugins:
          - pass
          - postgres
          - sudo
          - pylint 
          - python 
          - pip 
          - pyenv 
          - poetry 
          - poetry-env 
          - docker 
          - docker-compose 
          - git 
          - zsh-autosuggestions 
          - zsh-history-substring-search 
          - zsh-syntax-highlighting

    - role: avanov.pyenv
      vars:
        pyenv_path: "{{ home }}/pyenv"
        pyenv_owner: "{{ instance_owner }}"
        pyenv_global: "3.12.1"
        pyenv_update_git_install: false
        pyenv_enable_autocompletion: true
        pyenv_python_versions:
          - "3.12.1"

    #- role: staticdev.brave

    - role: guillermodotn.vscodium
      vars:
        vscodium_extensions:
          - PKief.material-icon-theme
          - IBM.output-colorizer

    - role: diademiemi.freetube
      vars:
        freetube_version: 0.20.0

  tasks:

    - name: Install packages
      ansible.builtin.dnf:
        name:
          - eassyeffects
          - shotwell
          - mpv
          - vim
          - git
          - pass
          - gnome-console

    - name: Done
      ansible.builtin.debug:
        msg: Set-up finished!!
